### ISSUE TITLE
Cannot run properly under GitHub Action

### ISSUE THREAD

**Issue by FtoPayRespec** [aufdenpunkt/python-safety-check#7]
When I use this package with:
```yml
- name: Check Python File Safety
   uses:
        aufdenpunkt/python-safety-check@master
```
It shows `[Errno 2] No such file or directory: '/github/workspace/./requirenments.txt'`
After checking the code I have, I see:
`requirements.txt` in my repo and in this repo finding require _n_ ments.txt
Could you fix it ASAP? Thx.
